MODEL:
  META_ARCHITECTURE: "PersFormer"
  BACKBONE:
    NAME: "build_mit_backbone"
  GRAVITY_ON: True
  LATITUDE_ON: True
  WEIGHTS: 'init_model_weights/ade_pretrained.pth'
  LATITUDE_DECODER:
    LOSS_WEIGHT: 1.0
    LOSS_TYPE: 'regression'
  GRAVITY_DECODER:
    LOSS_WEIGHT: 1.0
    LOSS_TYPE: 'regression'
DATASETS:
  TRAIN: ("gsv_train",)
  TEST: ("gsv_val",)
OUTPUT_DIR: "./exp/step01-gsv-perspective-pretrain"
TEST:
  EVAL_PERIOD: 2000
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.001
  STEPS: (40000, 60000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 2000
DATALOADER:
  NUM_WORKERS: 8
  AUGMENTATION: True
VIS_PERIOD: 200
